[project]
name = "cwic"
version = "0.1.0"
authors = [
    "Cyris Kissane <cyris@crystalai.org>",
    "Adam Klein <adam@crystalai.org>",
    "Niveditha Iyer <niveditha@crystalai.org>"]
description = ""
channels = ["https://prefix.dev/conda-forge", "pytorch", "nvidia"]

platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
preview = ["pixi-build"]

[feature.gpu]
platforms = ["linux-64", "linux-aarch64"]
[feature.gpu.system-requirements]
cuda = "12.0"
[feature.gpu.dependencies]
cuda-version = "12.8.*"
pytorch-gpu = "*"
[feature.gpu.pypi-dependencies]
hydra-core = ">=1.3"

[feature.cpu.dependencies]
pytorch-cpu = "*"
[feature.cpu.pypi-dependencies]
hydra-core = ">=1.3"

[feature.eval]
platforms = ["linux-64", "linux-aarch64"]
[feature.eval.system-requirements]
cuda = "12.0"
[feature.eval.dependencies]
cuda-version = "12.8.*"
pytorch-gpu = "*"
[feature.eval.pypi-dependencies]
hydra-core = "*"
lighteval = "==0.10.0"

[environments]
cpu = ["cpu"]
default = ["gpu"]
eval = ["eval"]

[pypi-dependencies]
wandb = "*"
transformers = "*"
matplotlib = "*"
wandb-core = "*"
scikit-learn = "*"
pre-commit = "*"
black = "*"
isort = "*"
flake8 = "*"
autoflake = "*"
docformatter = "*"
pyright = "*"
einops = "*"
accelerate = "*"
datasets = "==3.6.0"
requests = "*"
aiohttp = "*"
cwic = { path = ".", editable = true }

[dependencies]
python = "==3.12"

[pypi-options.dependency-overrides]
numpy = ">=1.26.4"
fsspec = ">=2025.7.0"

