[project]
name = "cwic"
version = "0.1.0"
authors = [
    "Cyris Kissane <cyris@crystalai.org>",
    "Adam Klein <adam@crystalai.org>",
    "Niveditha Iyer <niveditha@crystalai.org>"]
description = ""
channels = ["https://prefix.dev/conda-forge", "pytorch", "nvidia"]

platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
preview = ["pixi-build"]

[feature.gpu]
platforms = ["linux-64", "linux-aarch64"]
[feature.gpu.system-requirements]
cuda = "12.0"

[feature.gpu.dependencies]
cuda-version = "12.8.*"
pytorch-gpu = "*"
jax = "*"
datasets = "==4.0.0"

[feature.cpu.dependencies]
pytorch-cpu = "*"
jax = "*"
datasets = "==4.0.0"

[environments]
cpu = ["cpu"]
default = ["gpu"]

[pypi-dependencies]
flax = { git = "https://github.com/google/flax.git" }
optax = "*"
orbax-checkpoint = "*"
chex = "*"
wandb = "*"
transformers = "*"
gcsfs = "*"
jinja2 = "*"
fastapi = "*"
nltk = "*"
matplotlib = "*"
wandb-core = "*"
jaxtyping = "*"
scikit-learn = "*"
tensorflow-datasets = "*"
pre-commit = "*"
black = "*"
isort = "*"
flake8 = "*"
autoflake = "*"
docformatter = "*"
pyright = "*"
einops = "*"
accelerate = "*"
hydra-core = "*"
cwic = { path = ".", editable = true }

[dependencies]
python = "==3.12"
