
run_name: cwic-default

wandb_entity: null
wandb_project: cwic-iclr

teacher_model: unsloth/Llama-3.2-1B
student_model: null

max_length: 1024
batch_size: 8
grad_accum_steps: 8
kd_chunk_size: null

compile: false

max_grad_norm: 1000000.0

start_compute_reduction: 1.05
end_compute_reduction: 8.0
compute_reduction_steps: 5000

mse_layers: [5, 8]
mse_weight: 1.0

checkpoint_interval: 714

model:

  stripe_size: 1024
  head_stripe_size: 16384

  head_limit: null

  threshold_lr_scale: 10.0
  threshold_init: 0.01
  threshold_minimum: 0.01

  bandwidth: 0.1

  stats_beta: 0.99
  median_iters: 3

  # _attn_implementation: eager


dataset:

  path: aklein4/fineweb-edu-sample-10BT-shuffled

  split: train
  streaming: true


optimizer:

  lr: 5e-5
  weight_decay: 0.01

  betas: [0.9, 0.95]


lr_scheduler:

  name: linear

  num_warmup_steps: 100
  num_training_steps: 7500
